#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backend &

bspc monitor -d I II III IV # V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# Auto-Start Programs:
feh --bg-fill --randomize ~/Pictures/Wallpapers/* & # Wallpaper
eww daemon
