#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backend &

# Default 1 monitor with 4 workspaces
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    # Layout
    bspc monitor "$monitor" -d I II III IV V # VI VII VIII IX X
done

# Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
# change these values according to your system
# you can use `xrandr -q` to get the names of monitors
#INTERNAL_MONITOR="eDP"
#EXTERNAL_MONITOR="HDMI-A-0"
#if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    #bspc monitor "$EXTERNAL_MONITOR" -d 'I' 'II' 'III' 'IV'
    #bspc monitor "$INTERNAL_MONITOR" -d 'V' 'VI' 'VII' 'VIII'
    #bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
#else
    #bspc monitor "$INTERNAL_MONITOR" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
#fi

# Configs
bspc config focused_border_color "#ffffff"
bspc config border_width 0
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Rules
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# Auto-Start Programs:
feh --bg-fill --randomize ~/Pictures/Wallpapers/Episodes/ # Wallpaper
bash "${HOME}"/.config/eww/scripts/Workspaces/Generate.sh # EWW
