print_info() {
    prin ""
    info "$(color 15)󰍹" gpu
    info "$(color 15)" cpu
    info "$(color 15)" disk
    info "$(color 15)" memory
}

memory_percent="on"
memory_unit="gib"
cpu_speed="off"
cpu_cores="off"
disk_subtitle="none"
separator="᠎"
ascii_colors=(15 1)
