print_info() {
    prin "$(color 15)╭───╮"
    info "$(color 15)│ 󰍹 " gpu
    info "$(color 15)│  " cpu
    info "$(color 15)│  " disk
    info "$(color 15)│  " memory
    prin "$(color 15)├───┤"
    prin "$(color 15)│  │ $(color 8)󰫢 $(color 9)󰫢 $(color 10)󰫢 $(color 11)󰫢 $(color 12)󰫢 $(color 13)󰫢 $(color 14)󰫢 $(color 15)󰫢"
    prin "$(color 15)╰───╯"
}

memory_percent="on"
memory_unit="gib"
cpu_speed="off"
cpu_cores="off"
disk_subtitle="none"
separator="│"
ascii_colors=(15)
