#!/usr/bin/env bash

#  ╔╗ ┌─┐┌┬┐┌┬┐┌─┐┬─┐┬ ┬
#  ╠╩╗├─┤ │  │ ├┤ ├┬┘└┬┘
#  ╚═╝┴ ┴ ┴  ┴ └─┘┴└─ ┴

battery=/sys/class/power_supply/BAT0

status="$(cat "$battery/status")"
capacity="$(cat "$battery/capacity")"

icon() {
    [ "$status" = Charging ] && icon="./images/Battery/Charging.png" && echo "$icon" && exit

    if [ "$capacity" -gt "90" ]; then
        icon="./images/Battery/100.png"  # icon="󰁹"
    elif [ "$capacity" -gt "80" ]; then
        icon="./images/Battery/90.png"  # icon="󰂂"
    elif [ "$capacity" -gt "70" ]; then
        icon="./images/Battery/80.png"  # icon="󰂁"
    elif [ "$capacity" -gt "60" ]; then
        icon="./images/Battery/70.png"  # icon="󰂀"
    elif [ "$capacity" -gt "50" ]; then
        icon="./images/Battery/60.png"  # icon="󰁿"
    elif [ "$capacity" -gt "40" ]; then
        icon="./images/Battery/50.png"  # icon="󰁾"
    elif [ "$capacity" -gt "30" ]; then
        icon="./images/Battery/40.png"  # icon="󰁽"
    elif [ "$capacity" -gt "20" ]; then
        icon="./images/Battery/30.png"  # icon="󰁼"
    elif [ "$capacity" -gt "10" ]; then
        icon="./images/Battery/20.png"  # icon="󰁻"
    elif [ "$capacity" -gt "0" ]; then
        icon="./images/Battery/10.png"  # icon="󰁺"
    else
        icon="./images/Battery/0.png"  # icon="󰂎"
    fi

    echo "$icon"
}

percentage() {
    echo "$capacity%"
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percentage" ] && percentage && exit

exit
