#!/usr/bin/env bash

#  ╔╗ ┌─┐┌┬┐┌┬┐┌─┐┬─┐┬ ┬
#  ╠╩╗├─┤ │  │ ├┤ ├┬┘└┬┘
#  ╚═╝┴ ┴ ┴  ┴ └─┘┴└─ ┴

battery=/sys/class/power_supply/BAT0/

status=$(cat $(battery)status || echo 0)
capacity=$(cat $(battery)capacity || echo 0)

icon() {
    [ "$status" = 0 ] && [ "$capacity" = 0 ] && icon="./images/Battery/0.png" && echo "$icon" && exit
    [ "$status" = Charging ] && icon="./images/Battery/Charging.png" && echo "$icon" && exit

    if [ "$capacity" -gt 90 ]; then  # if [ "$capacity" -lt 9 ]; then
        icon="./images/Battery/100.png"  # icon="󰂎"
    elif [ "$capacity" -gt 80 ]; then  # elif [ "$capacity" -lt 17 ]; then
        icon="./images/Battery/85.png"  # icon="󰁺"
    elif [ "$capacity" -gt 70 ]; then  # elif [ "$capacity" -lt 25 ]; then
        icon="./images/Battery/85.png"  # icon="󰁻"
    elif [ "$capacity" -gt 60 ]; then  # elif [ "$capacity" -lt 33 ]; then
        icon="./images/Battery/65.png"  # icon="󰁼"
    elif [ "$capacity" -gt 50 ]; then  # elif [ "$capacity" -lt 41 ]; then
        icon="./images/Battery/65.png"  # icon="󰁽"
    elif [ "$capacity" -gt 40 ]; then  # elif [ "$capacity" -lt 51 ]; then
        icon="./images/Battery/45.png"  # icon="󰁾"
    elif [ "$capacity" -gt 30 ]; then  # elif [ "$capacity" -lt 61 ]; then
        icon="./images/Battery/45.png"  # icon="󰁿"
    elif [ "$capacity" -gt 20 ]; then  # elif [ "$capacity" -lt 71 ]; then
        icon="./images/Battery/25.png"  # icon="󰂀"
    elif [ "$capacity" -gt 10 ]; then  # elif [ "$capacity" -lt 81 ]; then
        icon="./images/Battery/25.png"  # icon="󰂁"
    elif [ "$capacity" -gt 0 ]; then  # elif [ "$capacity" -lt 91 ]; then
        icon="./images/Battery/10.png"  # icon="󰂂"
    else
        icon="./images/Battery/0.png"  # icon="󰁹"
    fi

    echo "$icon"
}

percentage() {
    [ "$status" = 0 ] && [ "$capacity" = 0 ] && capacity="Off" && echo "$capacity" && exit

    echo "$capacity%"
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percentage" ] && percentage && exit

exit
