print_info() {
    prin "$(color 15)╭╴ OS ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ Debian Linux"
    info "$(color 15)│ ᠎ ᠎ ├─╴ Kernel ᠎ ᠎ ᠎ " kernel
    info "$(color 15)│ ᠎ ᠎ ├─╴󱆃 Shell ᠎ ᠎ ᠎ ᠎ " shell
    info "$(color 15)│ ᠎ ᠎ ╰─╴󰏗 Package ᠎ ᠎ " packages
    prin "$(color 15)╰╴ Specs ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ ────"
    info "$(color 15) ᠎ │ ├─╴󰍹 GPU ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ " gpu
    info "$(color 15) ᠎ │ ├─╴ CPU ᠎ ᠎ ᠎ ᠎ ᠎ ᠎ " cpu
    info "$(color 15) ᠎ │ ├─╴ Disk ᠎ ᠎ ᠎ ᠎ ᠎ " disk
    info "$(color 15) ᠎ │ ╰─╴ Memory ᠎ ᠎ ᠎ " memory
    prin "$(color 15)╭─┴─╮"
    prin "$(color 15)│ 󰮯 │ ᠎ $(color 8)󰊠 $(color 9)󰊠 $(color 10)󰊠 $(color 11)󰊠 $(color 12)󰊠 $(color 13)󰊠 $(color 14)󰊠"
    prin "$(color 15)╰───╯"
}

memory_percent="on"
memory_unit="gib"
cpu_speed="off"
cpu_cores="off"
disk_subtitle="none"
separator=" ᠎ "
ascii_colors=(15 8 11)
